export const CHANGE_SEARCH = 'CHANGE_SEARCH';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';
export const GET_MOVIES_START = 'GET_MOVIES_START';
export const ADD_MOVIE_TO_WATCHLIST = 'ADD_MOVIE_TO_WATCHLIST';
export const ADD_MOVIE_FAIL = 'ADD_MOVIE_FAIL';